# Generated by Django 6.0.1 on 2026-01-24 15:56

import django_security_label.labels
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_security_label", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskedColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('uuid', models.UUIDField()),
                ('safe_text', models.TextField()),
                ('safe_uuid', models.UUIDField()),
                ('confidential', models.TextField()),
                ('random_int', models.IntegerField()),
            ],
            options={
                'indexes': [django_security_label.labels.AnonMaskSecurityLabel(fields=['text'], mask_function=django_security_label.labels.MaskFunction['dummy_catchphrase'], name='testapp_mas_text_6adba0_idx', provider='anon', string_literal='MASKED WITH FUNCTION anon.dummy_catchphrase()'), django_security_label.labels.AnonMaskSecurityLabel(fields=['uuid'], mask_function=django_security_label.labels.MaskFunction['dummy_uuidv4'], name='testapp_mas_uuid_18a3e6_idx', provider='anon', string_literal='MASKED WITH FUNCTION anon.dummy_uuidv4()'), django_security_label.labels.ColumnSecurityLabel(fields=['confidential'], name='testapp_mas_confide_030817_idx', provider='anon', string_literal='MASKED WITH VALUE $$CONFIDENTIAL$$'), django_security_label.labels.ColumnSecurityLabel(fields=['random_int'], name='testapp_mas_random__45b12e_idx', provider='anon', string_literal='MASKED WITH FUNCTION anon.random_int_between(0,50)')],
            },
        ),
    ]
