# Generated by Django 6.0.1 on 2026-02-16 13:11
from __future__ import annotations

from django.db import migrations, models

import django_security_label.labels


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaskedColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("uuid", models.UUIDField()),
                ("confidential", models.TextField()),
                ("number", models.IntegerField()),
            ],
            options={
                "indexes": [
                    django_security_label.labels.MaskColumn(
                        fields=["text"],
                        mask_function=django_security_label.labels.MaskFunction[
                            "dummy_catchphrase"
                        ],
                        name="maskedcolumn_text_devs",
                        policy="dsl_devs",
                        provider="dsl_devs",
                        string_literal="MASKED WITH FUNCTION anon.dummy_catchphrase()",
                    ),
                    django_security_label.labels.MaskColumn(
                        fields=["text"],
                        mask_function=django_security_label.labels.MaskFunction[
                            "dummy_catchphrase"
                        ],
                        name="maskedcolumn_text_analyst",
                        policy="dsl_analysts",
                        provider="dsl_analysts",
                        string_literal="MASKED WITH FUNCTION anon.dummy_catchphrase()",
                    ),
                    django_security_label.labels.MaskColumn(
                        fields=["uuid"],
                        mask_function=django_security_label.labels.MaskFunction[
                            "dummy_uuidv4"
                        ],
                        name="core_masked_uuid_82abbd_idx",
                        policy="anon",
                        provider="anon",
                        string_literal="MASKED WITH FUNCTION anon.dummy_uuidv4()",
                    ),
                    django_security_label.labels.AnonymizeColumn(
                        fields=["confidential"],
                        name="maskedcolumn_confid_devs",
                        provider="dsl_devs",
                        string_literal="MASKED WITH VALUE $$CONFIDENTIAL$$",
                    ),
                    django_security_label.labels.AnonymizeColumn(
                        fields=["confidential"],
                        name="maskedcolumn_confid_analysts",
                        provider="dsl_analysts",
                        string_literal="MASKED WITH VALUE $$CONFIDENTIAL$$",
                    ),
                    django_security_label.labels.AnonymizeColumn(
                        fields=["number"],
                        name="core_masked_number_bb30d7_idx",
                        provider="dsl_devs",
                        string_literal="MASKED WITH FUNCTION anon.random_int_between(0,50)",
                    ),
                ],
            },
        ),
    ]
